### ISSUE TITLE
How do we connect projects (Zoho) to customers (Wint)?

### ISSUE THREAD

**Issue by izaxon** [Konsultkooperativet/wintZohoInvoicing#3]

**Comment by mberglundmx** [comment]
Projects in Zoho will be connected to accounts in Zoho CRM
- One client account, and one (or more) member accounts

The member accounts in CRM will be identified by the consultants email address, The client account will be linked inside Zoho.

Clients in Wint be be created/updated as needed from information in Zoho CRM
